### ISSUE TITLE
Search: Does not submit upon hitting enter

### ISSUE THREAD

**Issue by rcass** [redacademy/it-winter-2018#10]
The search in the nav bar does not submit when you hit enter.

**Comment by 2lives** [comment]
var $searchInput = $('.search-field');
  $('.main-navigation .search-field').on('click', function (e) {
    e.preventDefault();
    $searchInput.focus();
  
    $(document).on('keypress', function (event) {
      if ($searchInput.val() !== '') {
        if (event.which == 13) {
          console.log('enter pressed');
          $('.search-form').submit();
        }
      }
    });
  });

this seems to do the trick!

**Comment by rcass** [comment]
Looks like it is functioning now 👍
