### ISSUE TITLE
Default Post Functionality: Set Featured Image

### ISSUE THREAD

**Issue by rcass** [redacademy/it-winter-2018#15]
More of a nice to have/future planning:

But when adding a new static page, if you add a feature image it does not appear. 
This would make the user feel like something is `broken`. 

If you have time, it would be best to just make the feature image display. You will have to do some CSS to ensure that it doesn't look totally broken or something like that.

**Comment by DakotaPaige** [comment]
Added featured image integration to template part of content-page to account for this, commit: 48d0b6ed00bc115dae7aa8f65cfd0af0042dc3d9
