### ISSUE TITLE
page-contact.php: Code to be Removed

### ISSUE THREAD

**Issue by rcass** [redacademy/it-winter-2018#21]
Here are few things I noticed that I think just need to be removed.

- [ ] https://github.com/redacademy/it-winter-2018/blob/aadfa0eae0dad1c4deb8156a34b7773247323aa9/themes/instanttheatre/page-contact.php#L25-L30

- [ ] https://github.com/redacademy/it-winter-2018/blob/aadfa0eae0dad1c4deb8156a34b7773247323aa9/themes/instanttheatre/page-contact.php#L49

**Comment by sslnyx** [comment]
removed
