### ISSUE TITLE
Remove all the calls to the Sidebar (since it is not being used)

### ISSUE THREAD

**Issue by rcass** [redacademy/it-winter-2018#23]
- [ ] https://github.com/redacademy/it-winter-2018/blob/aadfa0eae0dad1c4deb8156a34b7773247323aa9/themes/instanttheatre/page-show-list.php#L134

- [ ] https://github.com/redacademy/it-winter-2018/blob/aadfa0eae0dad1c4deb8156a34b7773247323aa9/themes/instanttheatre/page-hire-us.php#L118

- [ ] https://github.com/redacademy/it-winter-2018/blob/aadfa0eae0dad1c4deb8156a34b7773247323aa9/themes/instanttheatre/page-studio.php#L55

**Comment by GPChappell** [comment]
Sidebar call removed from all page templates
commit a201370847ce604f01fbde2aa7daf3437cc5331e
