### ISSUE TITLE
Assets Folder: Only keep what you need

### ISSUE THREAD

**Issue by rcass** [redacademy/it-winter-2018#25]
In ref to the assets folder, remember that in the root of the theme you only want the files which are necessary to the theme. 

So reminder to delete unnecessary files before a client hand off or launching.

**Comment by DakotaPaige** [comment]
Removed unused files from folder. Commits: 5c1b44b0500daf28b952a57f5d399f949b70a8e8, 0b1e31f15bbcceb88558087f3880a0747f369829

**Comment by rcass** [comment]
Nice 👍 

Just want to double check, but have the images be through a compressor? @DakotaPaige
