### ISSUE TITLE
refactor suggestion

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/it-winter-2018#26]
https://github.com/redacademy/it-winter-2018/blob/aadfa0eae0dad1c4deb8156a34b7773247323aa9/themes/instanttheatre/js/carousel.js#L3-L19

Since you are basically repeating the same thing you could try to use multiple selectors instead and see if that works...

e.g. 

````
$('.hire-us-grid, .testimonial-carousel-container, .studio-grid, .community-gallery-images, .show-cast-container').flickity({
   prevNextButtons: false
});
````

**Comment by GPChappell** [comment]
Refactored jQuery selectors as suggested
commit 07af12d68cc4ba1de93d161227794a14954c64ed
