### ISSUE TITLE
Post Types: Translatable Strings & Code Consistancy

### ISSUE THREAD

**Issue by rcass** [redacademy/it-winter-2018#27]
In the functionality plugin, I noticed that when registering the custom post types some of the post types had translatable strings `__x(   )` and some do not.

Basically, this functions but for the sake of code quality you need to agree on how you want this written.

Either with translatable strings:
![screen shot 2018-03-22 at 4 17 40 pm](https://user-images.githubusercontent.com/5028555/37803549-9649c42a-2dec-11e8-8739-6fe9094ace6b.png)
 Or no translatable strings:
![screen shot 2018-03-22 at 4 17 48 pm](https://user-images.githubusercontent.com/5028555/37803555-9df20a84-2dec-11e8-9e87-054b30a3a8b8.png)

Decide as a group how you want to format the code and adjust please 👌

**Comment by rcass** [comment]
If it helps, custom taxonomies that are registered do not have translatable strings. So you will need to be consistent with custom post types and  custom taxonomies.

**Comment by GPChappell** [comment]
All CPT now declared in same style. 
commit 64988ccb514099cace874908b74147143bcc796d
