### ISSUE TITLE
prefix of path constant is red functionality still

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/it-winter-2018#3]
Very minor however you should update any default prefixes to match your project e.g. instead of the constant being RF_DIR this could be IT_DIR

https://github.com/redacademy/it-winter-2018/blob/cf684effeca6adc3f68a3c56649aacfb086c7b23/plugins/it-functionality/it-functionality.php#L28

**Comment by 2lives** [comment]
updated.
