### ISSUE TITLE
remove ; after image src

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/it-winter-2018#6]
currently there's an extra ; in your html, not inside a php block, you can remove this.
It looks like it happens on line 29 as well

https://github.com/redacademy/it-winter-2018/blob/cf684effeca6adc3f68a3c56649aacfb086c7b23/themes/instanttheatre/header.php#L28

**Comment by 2lives** [comment]
<a class="desktop-rocket-logo" href="<?php echo esc_url(home_url('/') );?>"><img src="<?php echo get_template_directory_uri(); ?>/assets/logo/primary/black.png"/></a>
					<a class="circular-rocket-logo" href="<?php echo esc_url(home_url('/') );?>"><img src="<?php echo get_template_directory_uri(); ?>/assets/logo/circular/black.png"/></a>

updated.
