### ISSUE TITLE
function prefix

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/it-winter-2018#7]
Same comment as previous regarding namespaces and function prefixes.

Don't worry about fixing this at the moment however functions should be changed from the default red_starter to something like it_

https://github.com/redacademy/it-winter-2018/blob/cf684effeca6adc3f68a3c56649aacfb086c7b23/themes/instanttheatre/functions.php#L14

**Comment by DakotaPaige** [comment]
Done along with other issue in commit 64f2a325fb8a8688d5bcd98c985e496a24045e21
