### ISSUE TITLE
js name

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/it-winter-2018#8]
Another array where you can add namespace prefixes e.g. it_ or it-

Basically for each script and style you enqueue you can prefix the reference with your company/project name e.g. 'it-form' instead of 'form'

https://github.com/redacademy/it-winter-2018/blob/cf684effeca6adc3f68a3c56649aacfb086c7b23/themes/instanttheatre/functions.php#L133

**Comment by DakotaPaige** [comment]
Done as requested in functions.php, commit ID 64f2a325fb8a8688d5bcd98c985e496a24045e21
